import { useMutation, useQuery } from "@tanstack/react-query";
import { Link, router } from "expo-router";
import { useEffect, useState } from "react";
import { Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { api } from "../lib/api";
import { authClient } from "../lib/auth";
import { flushOutbox, queueCapture } from "../lib/outbox";
import { registerPushDevice } from "../lib/notifications";

const palette = { paper: "#F8F6F1", panel: "#FFFCF6", ink: "#24231F", muted: "#706C64", moss: "#2F6B55", line: "#E7E1D7", pale: "#EAF3EC" };

export default function Home() {
  const session = authClient.useSession(); const [capture, setCapture] = useState("");
  const now = useQuery({ queryKey: ["now"], queryFn: async () => { const { data, error } = await api.v1.now.get(); if (error) throw error; return data; }, retry: false });
  useEffect(() => { void flushOutbox(); if (session.data) void registerPushDevice(); }, [session.data]);
  const submit = useMutation({ mutationFn: async () => { const value = capture.trim(); if (!value) return; const id = await queueCapture(value); await flushOutbox(); setCapture(""); return id; } });
  if (!session.data) return <SafeAreaView style={styles.center}><Text style={styles.wordmark}>linnet</Text><Text style={styles.signInTitle}>Keep your direction close.</Text><Text style={styles.muted}>The private beta is available to invited Google accounts.</Text><Pressable style={styles.primary} onPress={() => authClient.signIn.social({ provider: "google", callbackURL: "/" })}><Text style={styles.primaryText}>Continue with Google</Text></Pressable></SafeAreaView>;
  const primary = now.data?.primaryGoal;
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.page}><View style={styles.top}><Text style={styles.wordmark}>linnet</Text><Pressable onPress={() => authClient.signOut()}><Text style={styles.muted}>Sign out</Text></Pressable></View><Text style={styles.eyebrow}>TODAY’S DIRECTION</Text><Text style={styles.title}>One meaningful move at a time.</Text><View style={styles.hero}><Text style={styles.eyebrowLight}>HIGHEST-LEVERAGE OUTCOME</Text><Text style={styles.heroTitle}>{primary?.title ?? "Tell Linnet what you’re trying to move forward."}</Text><Text style={styles.heroBody}>{now.data?.nextAction?.title ?? "Capture your first goal and Linnet will help form the plan."}</Text><Pressable style={styles.lightButton}><Text style={styles.lightButtonText}>Start the next move</Text></Pressable></View><View style={styles.sectionHead}><Text style={styles.sectionTitle}>Quick capture</Text><Text style={styles.muted}>Works offline</Text></View><View style={styles.capture}><TextInput value={capture} onChangeText={setCapture} placeholder="What changed?" placeholderTextColor={palette.muted} multiline style={styles.input} /><Pressable style={styles.send} onPress={() => submit.mutate()}><Text style={styles.primaryText}>{submit.isPending ? "Saving" : "Send"}</Text></Pressable></View><View style={styles.sectionHead}><Text style={styles.sectionTitle}>Your goals</Text><Link href="/goals"><Text style={styles.link}>See all</Text></Link></View><Pressable style={styles.goal} onPress={() => router.push("/goals")}><View><Text style={styles.goalTitle}>{primary?.title ?? "No active goal yet"}</Text><Text style={styles.muted}>{primary?.risk?.replace("_", " ") ?? "Ready when you are"}</Text></View><Text style={styles.arrow}>→</Text></Pressable></ScrollView></SafeAreaView>;
}

const styles = StyleSheet.create({ safe:{flex:1,backgroundColor:palette.paper},page:{padding:22,paddingBottom:40},center:{flex:1,justifyContent:"center",padding:28,backgroundColor:palette.paper},top:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",marginBottom:46},wordmark:{fontFamily:"serif",fontSize:32,fontWeight:"600",color:palette.ink},eyebrow:{fontSize:10,fontWeight:"700",letterSpacing:1.2,color:palette.muted,marginBottom:10},eyebrowLight:{fontSize:10,fontWeight:"700",letterSpacing:1.2,color:"#CFE5D6",marginBottom:14},title:{fontFamily:"serif",fontSize:41,lineHeight:45,color:palette.ink,marginBottom:28},hero:{backgroundColor:palette.moss,borderRadius:18,padding:24,marginBottom:30},heroTitle:{fontFamily:"serif",fontSize:29,lineHeight:34,color:"white"},heroBody:{color:"#E2F0E7",lineHeight:21,marginTop:12},primary:{alignSelf:"flex-start",backgroundColor:palette.moss,paddingHorizontal:18,paddingVertical:13,borderRadius:9,marginTop:24},lightButton:{alignSelf:"flex-start",backgroundColor:"white",paddingHorizontal:16,paddingVertical:11,borderRadius:9,marginTop:21},primaryText:{color:"white",fontWeight:"700"},lightButtonText:{color:palette.moss,fontWeight:"700"},muted:{color:palette.muted,lineHeight:20},signInTitle:{fontFamily:"serif",fontSize:43,lineHeight:47,color:palette.ink,marginTop:42,marginBottom:15},sectionHead:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",marginBottom:12},sectionTitle:{fontFamily:"serif",fontSize:24,color:palette.ink},capture:{backgroundColor:palette.panel,borderWidth:1,borderColor:palette.line,borderRadius:15,padding:12,marginBottom:31},input:{minHeight:65,color:palette.ink,textAlignVertical:"top",padding:8},send:{alignSelf:"flex-end",backgroundColor:palette.ink,borderRadius:8,paddingHorizontal:15,paddingVertical:9},link:{color:palette.moss,fontWeight:"600"},goal:{backgroundColor:palette.panel,borderColor:palette.line,borderWidth:1,borderRadius:14,padding:18,flexDirection:"row",justifyContent:"space-between",alignItems:"center"},goalTitle:{fontFamily:"serif",fontSize:21,color:palette.ink,marginBottom:5},arrow:{fontSize:25,color:palette.moss} });
